/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Rober
 */
import javax.swing.*;
import java.awt.*;

public class VentanaConfig extends javax.swing.JPanel {

    // Variable para almacenar el panel al que se va a cambiar el color
    private JPanel PanelBase;
    
    /**
     * Creates new form VentanaConfig
     */
    public VentanaConfig(JPanel PanelBase) {
        this.PanelBase = PanelBase;
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBorrarTodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModoOscuro = new javax.swing.JButton();
        BtnGuia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnModoClaro = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 461));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 461));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnBorrarTodo.setBackground(new java.awt.Color(209, 68, 71));
        btnBorrarTodo.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnBorrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarTodo.setText("Borrar Galeria");
        btnBorrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(872, Short.MAX_VALUE)
                .addComponent(btnBorrarTodo)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(btnBorrarTodo)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1100, 70));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modo de Color");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnModoOscuro.setBackground(new java.awt.Color(0, 51, 51));
        btnModoOscuro.setFont(new java.awt.Font("ROG Fonts", 1, 36)); // NOI18N
        btnModoOscuro.setForeground(new java.awt.Color(255, 255, 255));
        btnModoOscuro.setText("Oscuro");
        btnModoOscuro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModoOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoOscuroActionPerformed(evt);
            }
        });
        jPanel1.add(btnModoOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, -1));

        BtnGuia.setBackground(new java.awt.Color(0, 0, 51));
        BtnGuia.setFont(new java.awt.Font("ROG Fonts", 1, 36)); // NOI18N
        BtnGuia.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoAsistencia.png"))); // NOI18N
        BtnGuia.setText("Guia");
        BtnGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuiaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Configuracion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnModoClaro.setBackground(new java.awt.Color(0, 153, 153));
        btnModoClaro.setFont(new java.awt.Font("ROG Fonts", 1, 36)); // NOI18N
        btnModoClaro.setForeground(new java.awt.Color(255, 255, 255));
        btnModoClaro.setText("Claro");
        btnModoClaro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModoClaro.setPreferredSize(new java.awt.Dimension(230, 55));
        btnModoClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoClaroActionPerformed(evt);
            }
        });
        jPanel1.add(btnModoClaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModoOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoOscuroActionPerformed
            // Cambiar el color de fondo a claro
            if(PanelBase != null){
            PanelBase.setBackground(Color.DARK_GRAY);
            PanelBase.repaint();
        }
    }//GEN-LAST:event_btnModoOscuroActionPerformed
    
    private void btnModoClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoClaroActionPerformed
            // Cambiar el color de fondo a claro
        if(PanelBase != null){
            PanelBase.setBackground(Color.WHITE);
            PanelBase.repaint();
        }
        
    }//GEN-LAST:event_btnModoClaroActionPerformed

    private void BtnGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuiaActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuia;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnModoClaro;
    private javax.swing.JButton btnModoOscuro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
